[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "sakura"
authors = [{name = "Zhenghao Zhang, Jiamin Chen, Haoran Wu", email = "adamzhang@me.com, vitochanjm@gmail, haoran@link.cuhk.edu.hk"}]
dynamic = ["version", "description"]
